// lib/styles-data.js
// Master data for all 30 UI styles

export const UI_STYLES = [
  {
    id: 1,
    slug: "neumorphism",
    name: "Neumorphism",
    category: "Tactile",
    tag: "Soft UI",
    desc: "Soft dual-shadow raised surfaces. Monochromatic light backgrounds with pressed and extruded tactile feel.",
    keyTrait: "Soft dual-shadow raised surfaces",
    color: "#e0e5ec",
    accent: "#6c8ebf",
    textColor: "#444",
    dark: false,
    bestFor: [
      "Smart home control apps",
      "Music player interfaces",
      "Fitness & health dashboards",
      "IoT device controllers",
      "Meditation & wellness apps",
    ],
    websites: "Mobile apps, Smart Device UIs, Health & Wellness",
    previewBg: "linear-gradient(135deg, #e0e5ec 0%, #c8d0dc 100%)",
  },
  {
    id: 2,
    slug: "glassmorphism",
    name: "Glassmorphism",
    category: "Glass",
    tag: "Transparent",
    desc: "Frosted blur on vivid gradients. Semi-transparent layers with backdrop-filter creating layered depth.",
    keyTrait: "Frosted blur on vivid gradients",
    color: "#667eea",
    accent: "#764ba2",
    textColor: "#fff",
    dark: true,
    bestFor: [
      "SaaS landing pages",
      "Premium finance apps",
      "Music streaming platforms",
      "Creative agency websites",
      "NFT & crypto dashboards",
    ],
    websites: "SaaS Platforms, Finance Apps, Creative Agencies",
    previewBg: "linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f64f59 100%)",
  },
  {
    id: 3,
    slug: "neo-brutalism",
    name: "Neo-Brutalism",
    category: "Raw",
    tag: "Bold",
    desc: "Hard borders, offset shadows, raw aesthetic. High contrast, zero border-radius, intentional edge.",
    keyTrait: "Hard borders, offset shadows, raw",
    color: "#f5f500",
    accent: "#000",
    textColor: "#000",
    dark: false,
    bestFor: [
      "Startup landing pages",
      "Developer tool websites",
      "Portfolio sites",
      "Political campaign pages",
      "Art & design studios",
    ],
    websites: "Startups, Dev Tools, Portfolios, Design Studios",
    previewBg: "linear-gradient(135deg, #f5f500 0%, #ffe000 100%)",
  },
  {
    id: 4,
    slug: "flat-design",
    name: "Flat Design 2.0",
    category: "Clean",
    tag: "Semantic",
    desc: "Clean, shadow-free with vivid color tokens. Semantic color coding and clear visual hierarchy. Modern SaaS standard.",
    keyTrait: "Clean, semantic color, no shadows",
    color: "#4f46e5",
    accent: "#7c3aed",
    textColor: "#fff",
    dark: true,
    bestFor: [
      "Enterprise SaaS products",
      "Admin dashboards",
      "Project management tools",
      "E-commerce platforms",
      "Corporate websites",
    ],
    websites: "Enterprise SaaS, Admin Panels, E-commerce",
    previewBg: "linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)",
  },
  {
    id: 5,
    slug: "material-design",
    name: "Material Design 3",
    category: "System",
    tag: "Google",
    desc: "Google's M3 — dynamic color, tonal surfaces, rounded pill components. Expressive and accessible.",
    keyTrait: "Google's tonal rounded system",
    color: "#6750a4",
    accent: "#e8def8",
    textColor: "#fff",
    dark: true,
    bestFor: [
      "Android applications",
      "Google ecosystem products",
      "Consumer mobile apps",
      "Productivity tools",
      "Educational platforms",
    ],
    websites: "Android Apps, Google Products, Consumer Apps",
    previewBg: "linear-gradient(135deg, #6750a4 0%, #9c27b0 100%)",
  },
  {
    id: 6,
    slug: "skeuomorphism",
    name: "Skeuomorphism",
    category: "Physical",
    tag: "Textured",
    desc: "Mimics real physical objects — textures, gradients, depth. iOS 6 era, now retro-cool again.",
    keyTrait: "Mimics real physical objects",
    color: "#4a5568",
    accent: "#68d391",
    textColor: "#fff",
    dark: true,
    bestFor: [
      "Music & audio apps",
      "Retro game interfaces",
      "Vintage-themed stores",
      "Instrument simulators",
      "Premium luxury products",
    ],
    websites: "Audio Apps, Retro Games, Luxury Products",
    previewBg: "linear-gradient(180deg, #4a5568 0%, #2d3748 100%)",
  },
  {
    id: 7,
    slug: "aurora",
    name: "Aurora / Mesh Gradient",
    category: "Ambient",
    tag: "Gradient",
    desc: "Animated color blobs creating ethereal depth. Often combined with glass. SaaS hero sections.",
    keyTrait: "Animated blob color fields",
    color: "#7c3aed",
    accent: "#06b6d4",
    textColor: "#fff",
    dark: true,
    bestFor: [
      "AI product landing pages",
      "SaaS hero sections",
      "Creative portfolio sites",
      "Tech startup homepages",
      "Premium subscription apps",
    ],
    websites: "AI Products, Tech Startups, Premium SaaS",
    previewBg: "linear-gradient(135deg, #7c3aed 0%, #06b6d4 50%, #f43f5e 100%)",
  },
  {
    id: 8,
    slug: "dark-minimal",
    name: "Dark Minimal",
    category: "Dev",
    tag: "Obsidian",
    desc: "Near-black backgrounds, hairline borders, subtle contrast. Vercel, Linear, Raycast aesthetic.",
    keyTrait: "Near-black, hairline borders",
    color: "#09090b",
    accent: "#fafafa",
    textColor: "#fafafa",
    dark: true,
    bestFor: [
      "Developer tools & CLIs",
      "Code editors & IDEs",
      "DevOps dashboards",
      "API documentation sites",
      "Tech SaaS products",
    ],
    websites: "Dev Tools, Code Editors, DevOps, API Docs",
    previewBg: "linear-gradient(135deg, #09090b 0%, #18181b 100%)",
  },
  {
    id: 9,
    slug: "retro-y2k",
    name: "Retro / Y2K",
    category: "Nostalgia",
    tag: "Cyberpunk",
    desc: "Neon glows, scanlines, pixel fonts. 90s–2000s digital nostalgia. Dark base + electric accent colors.",
    keyTrait: "Neon glows, scanlines, nostalgia",
    color: "#1a0030",
    accent: "#ff00cc",
    textColor: "#fff",
    dark: true,
    bestFor: [
      "Music festival websites",
      "Gaming platforms",
      "Streetwear brands",
      "Retro-themed events",
      "Gen Z social apps",
    ],
    websites: "Music Festivals, Gaming, Streetwear, Events",
    previewBg: "linear-gradient(135deg, #1a0030 0%, #2d0048 50%, #3333ff 100%)",
  },
  {
    id: 10,
    slug: "claymorphism",
    name: "Claymorphism",
    category: "Tactile",
    tag: "3D Clay",
    desc: "3D clay-thick bottom shadow creating physical depth illusion. Playful, toy-like, consumer apps.",
    keyTrait: "3D clay-thick bottom shadow",
    color: "#fce4ec",
    accent: "#ff6b9d",
    textColor: "#fff",
    dark: false,
    bestFor: [
      "Children's education apps",
      "Food delivery platforms",
      "Consumer lifestyle apps",
      "Gaming UI elements",
      "Subscription box sites",
    ],
    websites: "Kids Apps, Food Delivery, Consumer Lifestyle",
    previewBg: "linear-gradient(135deg, #fce4ec 0%, #e8f5e9 50%, #e3f2fd 100%)",
  },
  {
    id: 11,
    slug: "bento-grid",
    name: "Bento Grid",
    category: "Layout",
    tag: "Dashboard",
    desc: "Mosaic dashboard tiles with mixed-size cells. Japanese lunch box inspired. Apple keynote aesthetic.",
    keyTrait: "Mosaic dashboard tiles",
    color: "#0f0f0f",
    accent: "#7c3aed",
    textColor: "#fff",
    dark: true,
    bestFor: [
      "Product feature showcases",
      "Apple-style marketing pages",
      "Portfolio homepages",
      "Analytics dashboards",
      "App feature landing pages",
    ],
    websites: "Product Pages, Portfolios, Feature Showcases",
    previewBg: "linear-gradient(135deg, #0f0f0f 0%, #1a1a2e 100%)",
  },
  {
    id: 12,
    slug: "dopamine-ui",
    name: "Dopamine UI",
    category: "Bold",
    tag: "Saturated",
    desc: "Max-saturated colors, almost painful brightness. Energizes users. Consumer apps, gaming, Gen Z.",
    keyTrait: "Max-saturated bold color",
    color: "#fff",
    accent: "#ff3d00",
    textColor: "#111",
    dark: false,
    bestFor: [
      "Social media platforms",
      "Gaming apps & sites",
      "Sports betting platforms",
      "Energy drink brands",
      "Gen Z fashion brands",
    ],
    websites: "Social Media, Gaming, Sports, Energy Brands",
    previewBg: "linear-gradient(135deg, #ff3d00 0%, #ffe600 33%, #00e676 66%, #2979ff 100%)",
  },
  {
    id: 13,
    slug: "terminal-cli",
    name: "Terminal / CLI",
    category: "Hacker",
    tag: "Dev",
    desc: "Green-on-black monospace, command prompts. Developer-native feel. CLI tools, hacker blogs.",
    keyTrait: "Green-on-black monospace",
    color: "#0d0d0d",
    accent: "#00ff41",
    textColor: "#00ff41",
    dark: true,
    bestFor: [
      "Developer portfolios",
      "Hacker news-style sites",
      "Open source project pages",
      "Cybersecurity tools",
      "Tech blogs & newsletters",
    ],
    websites: "Dev Portfolios, OSS Projects, Cybersecurity, Tech Blogs",
    previewBg: "linear-gradient(135deg, #0d0d0d 0%, #0a1a0a 100%)",
  },
  {
    id: 14,
    slug: "swiss-international",
    name: "Swiss / International",
    category: "Editorial",
    tag: "Grid",
    desc: "Grid-based, typography-led. Clean white space, structural red accents. Print design meets digital.",
    keyTrait: "Grid + typography led",
    color: "#fff",
    accent: "#ff0000",
    textColor: "#000",
    dark: false,
    bestFor: [
      "Architecture firm sites",
      "Fashion brand websites",
      "Museum & gallery sites",
      "Academic institutions",
      "Magazine & editorial sites",
    ],
    websites: "Architecture, Fashion, Museums, Magazines",
    previewBg: "linear-gradient(135deg, #fff 0%, #f5f5f5 100%)",
  },
  {
    id: 15,
    slug: "pastel-soft",
    name: "Pastel / Soft UI",
    category: "Soft",
    tag: "Friendly",
    desc: "Gentle muted tones, rounded everything. Notion-adjacent. Health, wellness, productivity apps.",
    keyTrait: "Gentle muted tones, friendly",
    color: "#fdf6ff",
    accent: "#9f7aea",
    textColor: "#553c9a",
    dark: false,
    bestFor: [
      "Mental health platforms",
      "Note-taking apps",
      "Productivity tools",
      "Women-focused brands",
      "Baby & parenting apps",
    ],
    websites: "Mental Health, Productivity, Wellness, Parenting",
    previewBg: "linear-gradient(135deg, #fdf6ff 0%, #e9d8fd 50%, #bee3f8 100%)",
  },
  {
    id: 16,
    slug: "maximalism",
    name: "Maximalism",
    category: "Visual",
    tag: "Chaos",
    desc: "Everything loud, layered, intentionally overwhelming. Clashing colors, multiple typefaces, overlapping patterns.",
    keyTrait: "Everything loud, layered, busy",
    color: "#1a0a2e",
    accent: "#ff006e",
    textColor: "#fff",
    dark: true,
    bestFor: [
      "Music artist websites",
      "Fashion brand campaigns",
      "Art gallery platforms",
      "Festival event pages",
      "Experimental creative studios",
    ],
    websites: "Music Artists, Fashion Campaigns, Art Galleries",
    previewBg: "linear-gradient(45deg, #ff006e, #fb5607, #ffbe0b, #8338ec, #3a86ff)",
  },
  {
    id: 17,
    slug: "monochromatic",
    name: "Monochromatic UI",
    category: "Visual",
    tag: "Single Hue",
    desc: "Single hue, all shades and tints. Harmony through restriction. Tonal gradients replace multi-color palettes.",
    keyTrait: "Single hue, all shades/tints",
    color: "#7f1d1d",
    accent: "#ef4444",
    textColor: "#fff",
    dark: true,
    bestFor: [
      "Brand identity microsites",
      "Product launch pages",
      "Luxury fashion stores",
      "Wine & spirits brands",
      "Premium cosmetics sites",
    ],
    websites: "Brand Microsites, Luxury Fashion, Premium Products",
    previewBg: "linear-gradient(135deg, #450a0a 0%, #991b1b 50%, #f87171 100%)",
  },
  {
    id: 18,
    slug: "typographic",
    name: "Typographic UI",
    category: "Visual",
    tag: "Type-Led",
    desc: "Type IS the design. No icons, no imagery — pure letterforms, scale contrast, and editorial grid.",
    keyTrait: "Type IS the design",
    color: "#f5f0e8",
    accent: "#1a1a1a",
    textColor: "#1a1a1a",
    dark: false,
    bestFor: [
      "Literary magazines",
      "Law firm websites",
      "Publishing houses",
      "Consulting agencies",
      "Premium newsletter sites",
    ],
    websites: "Literary Magazines, Law Firms, Publishing, Consulting",
    previewBg: "linear-gradient(135deg, #f5f0e8 0%, #e8e0d0 100%)",
  },
  {
    id: 19,
    slug: "grain-texture",
    name: "Grain / Noise Texture",
    category: "Visual",
    tag: "Analog",
    desc: "Film grain overlays add warmth and analog soul. Fights sterile perfection of flat design.",
    keyTrait: "Film grain overlays for warmth",
    color: "#2d1b69",
    accent: "#11998e",
    textColor: "#fff",
    dark: true,
    bestFor: [
      "Photography portfolio sites",
      "Indie music platforms",
      "Coffee & artisan food brands",
      "Film & cinema sites",
      "Craft & handmade product stores",
    ],
    websites: "Photography, Indie Music, Artisan Food, Cinema",
    previewBg: "linear-gradient(135deg, #2d1b69 0%, #11998e 100%)",
  },
  {
    id: 20,
    slug: "geometric",
    name: "Geometric / Abstract",
    category: "Visual",
    tag: "Abstract",
    desc: "Shapes as the primary visual system. Triangles, hexagons, precise angles form the entire visual language.",
    keyTrait: "Shapes as the core visual system",
    color: "#0a0a14",
    accent: "#00e5ff",
    textColor: "#fff",
    dark: true,
    bestFor: [
      "Architecture firms",
      "Engineering companies",
      "Data science platforms",
      "Blockchain projects",
      "Tech conference sites",
    ],
    websites: "Architecture, Engineering, Data Science, Blockchain",
    previewBg: "linear-gradient(135deg, #0a0a14 0%, #1a1a2e 100%)",
  },
  {
    id: 21,
    slug: "organic-blob",
    name: "Organic / Blob UI",
    category: "Visual",
    tag: "Fluid",
    desc: "Irregular fluid shapes that breathe and morph. No hard edges — biomorphic organic forms.",
    keyTrait: "Irregular fluid shapes, no hard edges",
    color: "#0f0c29",
    accent: "#ec4899",
    textColor: "#fff",
    dark: true,
    bestFor: [
      "Wellness & spa brands",
      "Organic food companies",
      "Children's creative apps",
      "Beauty & skincare brands",
      "Mindfulness platforms",
    ],
    websites: "Wellness, Organic Food, Beauty, Mindfulness",
    previewBg: "linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #ec4899 100%)",
  },
  {
    id: 22,
    slug: "card-based",
    name: "Card-Based UI",
    category: "Functional",
    tag: "Modular",
    desc: "Everything in modular card units. Scannable, flexible, infinitely composable. Foundation of modern web apps.",
    keyTrait: "Everything in contained card modules",
    color: "#f8f9fc",
    accent: "#4f46e5",
    textColor: "#1a1a2e",
    dark: false,
    bestFor: [
      "Job board platforms",
      "Real estate listing sites",
      "E-commerce product grids",
      "News & media aggregators",
      "Recipe & food platforms",
    ],
    websites: "Job Boards, Real Estate, E-commerce, News",
    previewBg: "linear-gradient(135deg, #f8f9fc 0%, #e0e7ff 100%)",
  },
  {
    id: 23,
    slug: "dashboard-ui",
    name: "Dashboard UI",
    category: "Functional",
    tag: "Data-Dense",
    desc: "Data-dense KPI-focused layouts for power users. Information architecture as aesthetic.",
    keyTrait: "Data-dense, KPI-focused layouts",
    color: "#0d1117",
    accent: "#1f6feb",
    textColor: "#c9d1d9",
    dark: true,
    bestFor: [
      "Analytics & BI platforms",
      "Financial trading apps",
      "CRM software",
      "DevOps monitoring tools",
      "Business intelligence tools",
    ],
    websites: "Analytics, Finance, CRM, DevOps Monitoring",
    previewBg: "linear-gradient(135deg, #0d1117 0%, #161b22 100%)",
  },
  {
    id: 24,
    slug: "magazine-editorial",
    name: "Magazine / Editorial",
    category: "Functional",
    tag: "Print",
    desc: "Print design rules applied to web. Column grids, pull quotes, typographic hierarchy.",
    keyTrait: "Print layout rules applied to web",
    color: "#fff",
    accent: "#e63946",
    textColor: "#1a1a1a",
    dark: false,
    bestFor: [
      "Online magazines & journals",
      "News media websites",
      "Long-form content platforms",
      "Brand storytelling sites",
      "Cultural institution sites",
    ],
    websites: "Online Magazines, News Media, Long-form Content",
    previewBg: "linear-gradient(135deg, #fff 0%, #f9f9f9 100%)",
  },
  {
    id: 25,
    slug: "parallax-scroll",
    name: "Parallax / Long Scroll",
    category: "Functional",
    tag: "Scroll",
    desc: "Storytelling through layered depth on scroll. Z-axis layers at different speeds — cinematic spatial illusion.",
    keyTrait: "Storytelling through scroll",
    color: "#000511",
    accent: "#fbbf24",
    textColor: "#fff",
    dark: true,
    bestFor: [
      "Product story pages",
      "Annual report microsites",
      "Luxury brand experiences",
      "Game launch sites",
      "Documentary & film sites",
    ],
    websites: "Product Stories, Luxury Brands, Game Launches",
    previewBg: "linear-gradient(180deg, #000511 0%, #0d1b2a 50%, #1b263b 100%)",
  },
  {
    id: 26,
    slug: "micro-interaction",
    name: "Micro-Interaction UI",
    category: "Functional",
    tag: "Motion",
    desc: "Animation as primary experience layer. Every click, toggle, transition carries weight. Delight in details.",
    keyTrait: "Animation as the main experience",
    color: "#fafafa",
    accent: "#4f46e5",
    textColor: "#1a1a1a",
    dark: false,
    bestFor: [
      "Onboarding flows",
      "Mobile app UIs",
      "Interactive product demos",
      "Gamified learning apps",
      "Consumer fintech apps",
    ],
    websites: "Mobile Apps, Onboarding Flows, Gamified Products",
    previewBg: "linear-gradient(135deg, #fafafa 0%, #e0e7ff 100%)",
  },
  {
    id: 27,
    slug: "vaporwave",
    name: "Vaporwave UI",
    category: "Niche",
    tag: "Retro",
    desc: "Pink/purple neon, perspective grids, synthwave sunsets. 80s corporate nostalgia through internet aesthetics.",
    keyTrait: "Pink/purple, Greek statues, retro grids",
    color: "#0a001f",
    accent: "#ff6ec7",
    textColor: "#fff",
    dark: true,
    bestFor: [
      "Synthwave music platforms",
      "Retro gaming sites",
      "80s themed event pages",
      "Aesthetic merch stores",
      "Lo-fi music channels",
    ],
    websites: "Synthwave Music, Retro Gaming, Lo-fi Channels",
    previewBg: "linear-gradient(180deg, #0a001f 0%, #2d0048 50%, #ff6ec7 100%)",
  },
  {
    id: 28,
    slug: "cottagecore",
    name: "Cottagecore / Nature UI",
    category: "Niche",
    tag: "Nature",
    desc: "Earthy, botanical, handcrafted. Warm cream backgrounds, serif fonts, dashed borders. Anti-tech, pro-cozy.",
    keyTrait: "Earthy, botanical, handcrafted feel",
    color: "#fdf8f0",
    accent: "#8b5e3c",
    textColor: "#5c3d2e",
    dark: false,
    bestFor: [
      "Organic food brands",
      "Herbal & botanical shops",
      "Farm-to-table restaurants",
      "Eco lifestyle brands",
      "Artisan craft stores",
    ],
    websites: "Organic Food, Herbal Shops, Farm-to-Table, Eco",
    previewBg: "linear-gradient(135deg, #fdf8f0 0%, #f0e8d8 100%)",
  },
  {
    id: 29,
    slug: "memphis-design",
    name: "Memphis Design",
    category: "Niche",
    tag: "80s",
    desc: "1980s Italian movement. Squiggles, primary colors, clashing patterns, geometric shapes. Kitsch as art.",
    keyTrait: "80s squiggles, primary colors, patterns",
    color: "#fff",
    accent: "#ff0066",
    textColor: "#1a1a1a",
    dark: false,
    bestFor: [
      "Kids' toy brands",
      "Retro-themed cafes & bars",
      "80s nostalgia events",
      "Playful startup brands",
      "Creative agency homepages",
    ],
    websites: "Kids Brands, Retro Bars, Playful Startups",
    previewBg: "linear-gradient(135deg, #fff 0%, #fff9c4 50%, #ffccdd 100%)",
  },
  {
    id: 30,
    slug: "pixel-art",
    name: "Pixel Art UI",
    category: "Niche",
    tag: "8-bit",
    desc: "Chunky retro pixel blocks, 8-bit palettes, CRT scanlines. Nostalgia for early computing.",
    keyTrait: "Everything in retro pixel blocks",
    color: "#1a1a2e",
    accent: "#00ff41",
    textColor: "#00ff41",
    dark: true,
    bestFor: [
      "Indie game studios",
      "Retro gaming platforms",
      "Game jam websites",
      "8-bit music channels",
      "Nostalgia tech stores",
    ],
    websites: "Indie Games, Retro Gaming, Game Jams, 8-bit Music",
    previewBg: "linear-gradient(135deg, #1a1a2e 0%, #0d0d1a 100%)",
  },
]

export const CATEGORIES = [
  { id: "all", label: "All 30" },
  { id: "Tactile", label: "Tactile" },
  { id: "Glass", label: "Glass" },
  { id: "Raw", label: "Raw" },
  { id: "Clean", label: "Clean" },
  { id: "Visual", label: "Visual" },
  { id: "Functional", label: "Functional" },
  { id: "Niche", label: "Niche" },
  { id: "Dev", label: "Dev" },
  { id: "Nostalgia", label: "Nostalgia" },
]
